services:
  - type: web
    name: myapp-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eyecareapp-db  # Must match your PostgreSQL DB name on Render
          property: connectionString